/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_resetta_iqa_iqa */

#ifndef _Included_com_resetta_iqa_iqa
#define _Included_com_resetta_iqa_iqa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_resetta_iqa_iqa
 * Method:    detectBestImageIndir
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_resetta_iqa_Iqa_detectBestImageIndir(JNIEnv *, jobject, jstring);

/*
 * Class:     com_resetta_iqa_iqa
 * Method:    initIqa
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_resetta_iqa_Iqa_initIqa(JNIEnv *, jobject,
                                                        jstring);

#ifdef __cplusplus
}
#endif
#endif
